/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/back.glb')
  const [selected, setSelected] = useState(props.bodyPart === 'back');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.BaseSpiderMan011.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={2.11} />
    </group>
  )
}

useGLTF.preload('/back.glb')
