/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/chest.glb');
  const [selected, setSelected] = useState(props.bodyPart === 'chest');

  return (
    <group ref={group} {...props} dispose={null}>
      {!selected && (
        <mesh
          onClick={() => setSelected(!selected)}
          geometry={nodes.BaseSpiderMan008.geometry}
          material={materials['Material.001']}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.11}
        />
      )}
      {selected && (
        <mesh
          onClick={() => setSelected(!selected)}
          onBlur={() => setSelected(!selected)}
          geometry={nodes.BaseSpiderMan008.geometry}
          rotation={[Math.PI / 2, 0, 0]}
          scale={2.11}
        >
          <meshStandardMaterial color={props.color} />
          </mesh>
      )}
    </group>
  );
}

useGLTF.preload('/chest.glb');
