/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/upper_legs.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.BaseSpiderMan005.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={2.11} />
    </group>
  )
}

useGLTF.preload('/upper_legs.glb')
